Great news4
duartenunes86/greatnews pull request #3
Opened 2023-08-15 09:35 UTC by duartenunes86

2023-08-15 09:53 UTC, Augs0 requested changes
A nice start to the tasks, Duarte, but some things to go back and look at again please. You seem particularly a bit confused about the different 404 errors we need to handle. If you need any help implementing the feedback, just let us know 😄

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +              expect.arrayContaining(["GET /api", "GET /api/topics","GET /api/articles",  ]))
If we test like this, we will have to keep coming back to change the test with each endpoint added. How do you think we could create a test that will not need to be updated every time?

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +            expect(response.body.endpoints).toEqual(expect.any(Object));
Please remember that both objects and arrays have a data type of object, so this would pass in both cases

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +      describe('GET /api/articles/:article_id', () => {
It looks like you have started the next task here as well. Please keep each task on its own branch. This is task 3 you submitted but the code here is task 4.

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +              console.log(response.body)
We should remove console logs before pushing work. They are only intended to be used for debugging

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +                expect.arrayContaining(["author",
If we are checking a specific article, we want to make sure all the content matches exactly e.g. that the id is indeed 1, that the title is the string we expect, etc

2023-08-15 09:53 UTC, Augs0 commented on __tests__/index.tests.js
> +          .get('/api/articless/1')
This is testing the 404 error handler you already tested. We need to test a different 404 here which is caused by no records being found e.g. if our article id is 5000

2023-08-15 09:53 UTC, Augs0 commented on controllers/articles-controllers.js
> +    console.log("fjdijsoijdifjdoijdi")
????

2023-08-15 09:53 UTC, Augs0 commented on app.js
There doesn't appear to be any error handler in your app so any errors, like 404 and 400 for the single article, won't be handled

2023-08-16 08:49 UTC, poppymcd requested changes
Some feedback to be enacted on tests and error handling specifically, so complete that carefully on the correct branch and submit another pull request 🙂

2023-08-16 08:49 UTC, poppymcd commented on controllers/articles-controllers.js
> +            if (results.length===0) {res.status(404).send({ msg:'article doesn\'t exist' });
Deciding if there's an error or not should be done in the model, not the controller so the error can be sent to the controller and then onto your error handling middleware. Look at previous examples of Promise.reject() in the model for hints on how to do this

2023-08-16 08:49 UTC, poppymcd commented on controllers/articles-controllers.js
> +      if (article.length===0 && !isNaN(article_id)) {res.status(404).send({ msg:'article doesn\'t exist' });
You should be finding errors in the model to pass back to your .catch(), see my comments below

2023-08-16 08:49 UTC, poppymcd commented on __tests__/index.tests.js
> +            expect(response.body.endpoints).toEqual(expect.any(Object));
Agree with August's comment, the test on line 56 to expect any object isn't a good test. Maybe remove this and keep the object.keys test

2023-08-16 08:49 UTC, poppymcd commented on __tests__/index.tests.js
> +              expect(response.body.results).toEqual(expect.any(Object));
I would take out the ```expect.any(Object)``` test here for the reasons August explained before, and keep the ```Object.keys``` part below

2023-08-16 08:49 UTC, poppymcd commented on controllers/articles-controllers.js
> +        console.log(id)
remember to take out console.logs before pushing code

2023-08-16 08:49 UTC, poppymcd commented on __tests__/index.tests.js
> +            .get(`/api/articles/1`)
Agree with August, you should change this to make sure that the id is 1, the title is 'Living in the shadow of a great man', author is 'mitch' or whatever your first article is

2023-08-16 13:24 UTC, itsaliabdallah commented on models/api-models.js
> +}
We shouldn't have a model for this it should exist in your controller since we are not interacting with the database.

2023-08-16 13:29 UTC, itsaliabdallah commented on controllers/articles-controllers.js
> +
as previously mentioned this logic should be handled in the model so that it can be passed onto the controller.

2023-08-16 13:52 UTC, duartenunes86 commented
I was told to merge all this into my project because there are a lot of branches

2023-08-16 13:52 UTC, merged